language: python
cache:
  pip: true
  directories:
    - node_modules
python:
  - 3.6
install:
  - nvm install 8
  - pip install --upgrade coala-bears
  - yarn
  - export PATH="$PATH:node_modules/.bin"
  - which eslint
script:
  - coala --ci -V && yarn run eslint && yarn run stylelint && yarn run test:coverage
